language: generic
services:
  - docker

before_install:
  - docker build -t vgrechin/react-test -f ./client/Dockerfile.dev ./client

script:
  - pushd client
  - npm install
  - docker run -e CI=true -v $(pwd):/usr/app vgrechin/react-test npm test -- --coverage
  - popd

after_success:
  - docker build -t vgrechin/multi-client ./client
  - docker build -t vgrechin/multi-nginx ./nginx
  - docker build -t vgrechin/multi-server ./server
  - docker build -t vgrechin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vgrechin/multi-client
  - docker push vgrechin/multi-nginx
  - docker push vgrechin/multi-server
  - docker push vgrechin/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "eu-north-1"
  app: "Multidocker"
  env: "Multidocker-env"
  bucket_name: elasticbeanstalk-eu-north-1-334453841210
  bucker_path: "DockerReact"
  on:
    branch: master

