version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: 'redis:alpine'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: server
    volumes:
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=password
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: client
    volumes:
      - ./client:/usr/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: worker
    volumes:
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
